print("Ingresa 1 patada dinamica")
num1=int(input())
print("Ingresa 2 patadas dinamicas")
num2=int(input())
print("Ingresa 3 patadas dinamicas")
num3=int(input())
print("Ingresa 4 patadas dinamicas")
num4=int(input())
print("Ingresa 5 patada dinamica")
num5=int(input())
print("Ingresa 6 patadas dinamicas")
num6=int(input())
print("Ingresa 7 patadas dinamicas")
num7=int(input())
print("Ingresa 8 patadas dinamicas")
num8=int(input())