print("Ingresa 1 puerta interna")
num1=int(input())
print("Ingresa 2 puertas internas")
num2=int(input())
print("Ingresa 3 puertas internas")
num3=int(input())
print("Ingresa 4 puertas internas")
num4=int(input())
print("Ingresa 5 puertas internas")
num5=int(input())
print("Ingresa 6 puertas internas")
num6=int(input())
print("Ingresa 7 puertas internas")
num7=int(input())
print("Ingresa 8 puertas internas")
num8=int(input())